Merging Feedback Branch into Main
AurorinhaBoreal/PersonCRUD pull request #6
Opened 2024-05-17 12:59 UTC by AurorinhaBoreal

This branch is being merge in main because development branch is older. After this merge will do the merge in development and the futures one will be there.

In this merge the following topics were addressed:
- [x] Mapper na Mão - Com Builder | ou Mapstruct

- [x] DTO's separados em Request (ja feitos) e Responses

- [x] Colocar Builder nas entidades

- [x] Trocar @data por @Getter e @Setter

- [x] Transformar DTO's em Record

- [x] Seguir padronização nos "ID"s para minuscula

- [x] Colocar Idade do ResponsePersonDTO

- [x] Tornar PageableDTO in ResponseDTO e retirar ID e colocar age

- [x] Colocar @‌Transaction em métodos que alterem informações no banco

Topics thats still need to be implemented:
- Fazer método para findByCPF ao invés de ID (Com exceção NotFound)
- Verificar Lógica de PageableException (GetInfoException)
- Mudar Lógica para verifyMainAddress (address desnecesário) retirar forEach
- Retirar tryCatch, deixar lançar exceção padrão e tratar exceções junto com a causa
- Criar Stub em TODOS os testes unitários
- Realizar Teste de Integração
- Realizar Teste Ponta a Ponta

Problerms Know:

- Because of the change in the calcAge Logic, the age is now calculated when a response is requested. But for now is only working when getting a Response through pageable. In a future merge i'll make the age be calculated when listAll Persons is called

2024-05-20 23:01 UTC, DRodrigues17 requested changes

2024-05-21 15:14 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/dto/RequestAddressDTO.java
Feedback Added in commit [feedback: Change DTO and Mappers Files Structure](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/6b6ac0075fbd3cf961f53841c43320adc7052f0b)

2024-05-21 15:15 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/dto/RequestAddressDTO.java
> +    @Size(min = 7, max = 12, message = "Informe um código postal válido")
Feedback Added in [feedback: Change Validation and Other messages to English](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/bb23cccdbd5219fe1553b9c6f1013138acbb8dd9)

2024-05-21 15:25 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/service/AddressService.java
>              repositoryA.save(addressOriginal);
Feedback Resolved in commit 
[refactor: Create a Method to FindPerson and replaced every findById to findByCpf](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/2d2caab0d11c9c6f94d0611f4efe5b82c5b553ae)

2024-05-21 17:58 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/controller/PersonController.java
> +        Person person = PersonMapper.INSTANCE.dtoToPerson(personDTO);
Feedback Implemented in [
feedback: Let SpringBoot call Mapper same Instance](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/dca2a17ba3bd5ef27638e02d91cd9e372ca5cdc9)

2024-05-21 17:58 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/service/AddressService.java
> +            ResponseAddressDTO responseAddress = AddressMapper.INSTANCE.addressToDto(address);
Feedback Implemented in
[feedback: Let SpringBoot call Mapper same Instance](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/dca2a17ba3bd5ef27638e02d91cd9e372ca5cdc9)

2024-05-21 18:45 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/controller/PersonController.java
> +        Person person = PersonMapper.INSTANCE.dtoToPerson(personDTO);
This commit was reverted! After a meeting we discovered that ".INSTANCE" only instanciates the Mapper one time. Font here: https://mapstruct.org/documentation/1.5/reference/html/#mappers-factory

2024-05-21 19:21 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/service/AddressService.java
> +                throw new CreateAddressException("Ja existe um endereço principal!"
Após termos essa conversa no feedback, eu fiquei um pouco em dúvida de como eu iria implementar, no fim eu acabei colocando um "hasTrueMainAddress" na tabela de usuário. Agora ele faz a verificação se o endereço criado, atualizado ou deletado é um mainAddress (tendo um método pra cada uma dessas funções) e caso for verdade, ele irá mudar o estado desse atributo.

Essa lógica pode ser vista no AddressService e Person a partir do commit: [
refactor: Change MainAddress Logic, PersonDTO and Add Person Entity Attribute](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/cb6d1a2e03d4e1b910df4277a19ec1fb57265e80)

Olhando em retrospecto... Acabou ficando com código maior, eu achei mais fácil de ler e entender a lógica... Mas talvez não valha a pena

2024-05-21 19:43 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/entity/Address.java
> +    public Address(RequestAddressDTO address) {
Eu não sei se eu entendi muito bem... Tipo... Esse construtor é pro próprio mapper fazer a criação e transformar um DTO em Entidade... Se eu for tirar o código quebra... Na teoria o @Builder torna esse construtor obsoleto, mas na prática não é isso que acontece ksks

Eu vi o projeto dos meus outros colegas, todos eles tem esse construtor da Entidade também.

Se puder especificar o que você quer, eu posso analisar melhor se tem como de alguma forma eu tirar esse construtor dai

2024-05-22 11:59 UTC, DRodrigues17 requested changes
vamos procurar mandar menos arquivos nos próximos pull requests

2024-05-22 12:03 UTC, DRodrigues17 commented on src/main/java/com/db/crud/person/service/AddressService.java
> +                throw new CreateAddressException("Ja existe um endereço principal!"
eu vi ali e não sei também se faz muito sentido, acho que poderíamos parear depois pra ver isso

2024-05-22 12:04 UTC, DRodrigues17 commented on src/main/java/com/db/crud/person/entity/Address.java
> +    public Address(RequestAddressDTO address) {
acredito que esses métodos deveriam estar no mapper, pois não vejo sentido em ter uma classe responsável por essa conversão se a própria entidade já é capaz de fazer isso

2024-05-22 20:52 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/service/AddressService.java
> +                throw new CreateAddressException("Ja existe um endereço principal!"
Refatoração do método de verificação do endereço principal feita em reunião. Mudanças a partir do commit:  [
feedback: Refactor verifyMainAddress logic in Address workflow](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/b7a800caa86dbdf12b62e60a9f731dfe06bd3d73)

2024-05-22 20:53 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/entity/Address.java
> +    public Address(RequestAddressDTO address) {
Feedback Adicionado no Commit [
feedback: Remove constructors from Entities and use Builder in Mapper](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/832ba065d7f8afedef29e8f09b142332754d02d9)

2024-05-22 20:55 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/controller/PersonController.java
> +    private PersonMapper personMapper;
Sim! Nós tinhamos, mas eu fiz alguma coisa errada e acabei enviando sem. Consertei no último commit: [
fix: Resolve rebase conflicts](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/84d9af6384288e22fa06408483e73fe86511d537)

2024-05-22 20:56 UTC, AurorinhaBoreal commented on src/test/java/com/db/crud/person/PersonServiceTests.java
> +        personDTO = new RequestPersonDTO("Aurora", "Kruschewsky", "37491502814", LocalDate.of(2004, 05, 14));
Esses testes eu estou mudando ainda! Ta certo... Mas no meu repositório local, acho que até amanhã de manhã eu subo os PersonTest e AddressTest

2024-05-22 20:57 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/service/AddressService.java
> +        log.info("The address is the main Address? "+addressOriginal.isMainAddress());
Era pra debugar, tinha até esquecido dele, vou retirar e ja fecho essa Review.

2024-05-22 20:59 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/service/PersonService.java
> +        log.info("Pessoas Registradas:");
Sim! Eu acabei escrevendo no inicio da lógica com a mentalidade que de alguma forma aparecia as pessoas no console... Ou algo do tipo, vou mudar pra "Buscando pessoas..." pra indicar que a ação está sendo feita e não confundir

2024-05-22 21:37 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/service/AddressService.java
> +        log.info("The address is the main Address? "+addressOriginal.isMainAddress());
Feedback Adicionado no commit: [feedback: Implement Small fixes that don't affect logic](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/f3607b4e786b34c9567f68dc591a9cc4ae982618)

2024-05-22 21:38 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/exception/ErrorHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
Review Adicionada ao código no commit: [feedback: Refactor Person and AddressNotFoundException to ObjectNotFoundException](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/9cd4f5971d6c24de4e4d473b0ef8f9defe91a3aa)

2024-05-22 22:02 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/dto/response/AddressResponse.java
> +    public AddressResponse(Address address){
Sim! Você ta mais que certo! Aproveitei a reunião de mais cedo e fiz a mesma coisa que fizemos com o dtoToPerson. Tirei o construtor do dto, coloquei um builder e construi o mesmo direto no Mapper! Ta dando um pequeno problema com o pageable... Pq o Dto não tem uma lista de endereços e no fim ele acaba só mostrando os itens do dto... Estranhamente caso usemos o construtor dentro do DTO isso não acontece... Eu vou ver isso com calma amanhã de manhã e tento achar uma solução...

2024-05-22 22:11 UTC, AurorinhaBoreal commented on src/main/java/com/db/crud/person/dto/response/AddressResponse.java
> +    public AddressResponse(Address address){
Eu... Não coloquei o addresses no builder, vou deixar o textão ai só pra você colocar minha evolução lá no PDI ksksks

Dito isso, feedback implementado no commit: [feedback: Remove Constructor from ResponseDTO and Create Builder in Mapppers](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/80d2995886c7ca1c5690354f2f2f6b4468c049f7)

2024-05-23 18:46 UTC, DRodrigues17 approved these changes
esse meu comentário pode ser alterado em um proximo PR

2024-05-23 18:46 UTC, DRodrigues17 commented on src/test/java/com/db/crud/person/AddressServiceTests.java
> +	}
Aqui n vejo sentido em existir esse before each, as variaveis podiam ja ser definidas com seus valores entre a linha 55 e 60

2024-05-23 20:21 UTC, AurorinhaBoreal commented on src/test/java/com/db/crud/person/AddressServiceTests.java
> +	}
Feedback Implementado no commit: 
[feedback: Remove Unnecessary BeforeEach Annotation](https://github.com/AurorinhaBoreal/PersonCRUD/pull/6/commits/62b366b979affa8f48f8e540f3b9f8ca115affd8)

2024-05-23 20:21 UTC, AurorinhaBoreal commented
Closing this branch and merging it to main!

2024-05-23 20:22 UTC, merged